spring:
  application:
    name: haiguitang-backend
  profiles:
    active: dev





#  autoconfigure:
#    exclude:


server:
  servlet:
    context-path: /api
#    session:
#      timeout: 30m
#      cookie:
#        http-only: true
#        secure: false


app:
  name: haiguitang-backend


